name: "MiniDLNA"
description: DLNA-Server
url: https://github.com/thkopp/hassio-addons/tree/main/addon-minidlna
version: "0.0.3"
slug: "minidlna"
init: "false"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: "true"
options:
  music: "/media/music"
  inotify: "no"
schema:
  media_database: "str"
  inotify: "str"
