name: "Hello world"
description: "My first real add-on!"
version: "1.1.19"
slug: "hello_world"
init: false
arch:
  - arm64
  - amd64
image: "ghcr.io/thkopp/addon-helloworld"
startup: services
ports:
  8000/tcp: 8000
