name: "mDNS Test Add-on"
description: "Ein einfaches Add-on, das einen mDNS/zeroconf Dienst broadcastet."
version: "0.0.3"
slug: "mdns_test"
arch:
  - amd64
  - aarch64
  - armv7
startup: "application"
boot: "manual"
host_network: true
ingress: false

ports:
  8080/tcp: 8080
  5353/udp: 5353

map:
  - config:rw

schema:
  mdns_name: str?
  mdns_port: int?

options:
  mdns_name: "test-mdns-device"
  mdns_port: 8080
