name: "mDNS Test Addon"
version: "0.0.8"
slug: "addon-mdns-example"
description: "Minimal mDNS test addon"
arch:
  - amd64
  - aarch64

startup: "application"
boot: "manual"

host_network: true
services:
  - dbus:system

image: ghcr.io/thkopp/addon-mdns-example
image_auth:
  username: ghcr_user
  password: ghcr_token

ingress: false
ports:
  8080/tcp: 8080
  5353/udp: 5353

options:
  ghcr_user: "thkopp"
  ghcr_token: "ghp_xxxxx12345TOKEN"
  device_name: "mdns-test-addon"
  port: 8080

schema:
  ghcr_user: str
  ghcr_token: str
  device_name: str?
  port: int?
