name: "mDNS Test Addon"
version: "0.0.8"
slug: "addon-mdns-example"
description: "Minimal mDNS test addon"
arch:
  - amd64
  - aarch64

startup: "application"
boot: "manual"

host_network: true

image: ghcr.io/thkopp/addon-mdns-example

ingress: false
ports:
  8080/tcp: 8080
  5353/udp: 5353

options:
  device_name: "mdns-test-addon"
  port: 8080

schema:
  device_name: str?
  port: int?
