name: "mDNS Example Addon"
version: "0.0.4"
slug: "addon-mdns-example"
description: "Minimal mDNS test addon"
arch:
  - amd64
  - armv7
startup: "application"
boot: "manual"
host_network: true
image: "ghcr.io/thkopp/addon-mdns-example:latest"
ingress: false

ports:
  8080/tcp: 8080
  5353/udp: 5353

map:
  - config:rw

schema:
  mdns_name: str?
  mdns_port: int?

options:
  mdns_name: "test-mdns-device"
  mdns_port: 8080
