name: "Shelly Emulator"
description: "Simuliert Shelly-Geräte mit lokalen Sensorwerten aus Home Assistant. Exponiert eine REST-API und mDNS für die LAN-Integration."
version: "1.0.0"
slug: "shelly_emulator"

init: false

arch:
  - amd64
  - armv7
  - aarch64

ports:
  8080/tcp: 8080
  5683/udp: 5683

options:
  device_name: "shelly-emu"
  port: "8080"
  mDNS: "true"
  coap: "false"
  device_id: "shelly-emulator-1"
  relays:
    - "0:switch.kitchen_socket"
  sensors:
    - "temperature:sensor.livingroom_temperature"
  ha_token: ""

schema:
  device_name: "str"
  port: "int"
  mDNS: "bool"
  coap: "bool"
  device_id: "str"
  relays:
    - "str"
  sensors:
    - "str"
  ha_token: "str"
